name: bubuy
description: Aplikasi berita hewan Bubuy.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependensi Inti Proyek
  http: ^1.2.1
  provider: ^6.1.2
  flutter_secure_storage: ^9.0.0 # Kembali menggunakan ini untuk keamanan token
  fluttertoast: ^8.2.6
  flutter_launcher_icons: ^0.14.4
  cupertino_icons: ^1.0.6
  another_carousel_pro: ^1.0.1
  shared_preferences: ^2.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/bubuy.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/